use_frameworks!

target 'EagleSDK_Example' do
  pod 'EagleSDK', :path => '../'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SSZipArchive'
  pod 'Masonry', '~> 1.1.0'
  
  target 'EagleSDK_Tests' do
    inherit! :search_paths

  end
end
